services:
  postgres:
    build:
      context: .
      dockerfile: postgres
    image: "allocatron-db-image"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - allocatron-db:/data/postgres-allocatron
    ports:
      - "5433:5432"
    restart: unless-stopped
volumes:
  allocatron-db:
    external: true
